3 switch setup neo4j
Brawdunoir/dionysos-server pull request #13
Opened 2022-05-30 19:54 UTC by WhiteDiamondz

2022-05-30 19:55 UTC, WhiteDiamondz commented
Ah bah le package jwt que j'avais apparemment c'est poubelle xptdrrr

2022-05-30 20:14 UTC, WhiteDiamondz commented
That's better

2022-05-31 20:07 UTC, Brawdunoir commented on routes/users.go
> +// var validate = validator.New()
Hiiii, ça veut push du code commenté aled.

2022-05-31 20:07 UTC, Brawdunoir commented on pkg/users/register.go
> +//func(writer http.ResponseWriter, request *http.Request) {
Code commenté

2022-05-31 20:13 UTC, Brawdunoir requested changes
Hey, would be awesome to make this MR as clean and as little as possible, so I suggest :
- Remove commented code
- Re-add gin (without gin, it is not an API anymore ! ;-) ) and the ping/pong GET request
- Remove example (can be stashed on local to serve its purpose for another issue —like CRUD on user)

2022-05-31 20:17 UTC, Brawdunoir commented on pkg/users/login.go
> +}
This example is out of scope of this issue. Add link to the online example in comments on other linked issues ;)

2022-05-31 20:17 UTC, Brawdunoir commented on pkg/users/register.go
> +}
This example is out of scope of this issue. Add link to the online example in comments on other linked issues ;)

2022-05-31 20:17 UTC, Brawdunoir commented on pkg/users/repository.go
> +}
Same

2022-06-01 16:05 UTC, WhiteDiamondz commented
As you probably know gin is not required for the code to be an API !
Without it it can still be one ;)
However, by all means we can use this solution, I'll put it and keep the examples for the corresponding issues

2022-06-01 18:15 UTC, Brawdunoir approved these changes

2022-06-01 18:32 UTC, merged