1 add user crud 1
Brawdunoir/dionysos-server pull request #19
Opened 2022-06-07 13:15 UTC by WhiteDiamondz

2022-06-07 18:45 UTC, Brawdunoir requested changes
Replace context.TODO with a real context

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	}
```suggestion
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not found"})
		log.Printf("Failed to read documents: %v", err)
		return
	}
```

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	}
```suggestion
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not created"})
		log.Printf("Failed to create documents: %v", err)
		return
	}
```

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User created", "id": meta.Key})
Message a bit useless

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User found", "user": result})
Message a bit useless

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	}
```suggestion
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not modified"})
		log.Printf("Failed to modify user: %v", err)
		return
	}
```

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User modified", "id": meta.Key})
Message a bit useless

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User deleted", "id": meta.Key})
Message a bit useless

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	}
```suggestion
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not deleted"})
		log.Printf("Failed to delete user: %v", err)
		return
	}
```

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	}
Is it really needed ? Cannot we use directly `user` ?

2022-06-07 18:45 UTC, Brawdunoir commented on routes/user.go
> +	var result models.User
Prefer to declare var at the beginning of function

2022-06-08 16:01 UTC, WhiteDiamondz commented on routes/user.go
> +	}
Not sure I understand, we only want here to update the username. Where you referring about changind the User object to have a field name "username" instead?

2022-06-09 19:21 UTC, Brawdunoir requested changes

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		log.Printf("Failed to access collection: %v", err)
Renvoyer une erreur interne

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not found"})
Virer message et mettre une erreur 404 (au autre plus précise)

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		log.Printf("Failed to access collection: %v", err)
Renvoyer erreur et return

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"message": "User not created"})
Virer message et mettre une erreur 404 (au autre plus précise)

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User created", "id": meta.Key})
Enlever message

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		log.Printf("Failed to access collection: %v", err)
Mettre erreur et return

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +	}
Did you try with user only ?

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +		log.Printf("Failed to access collection: %v", err)
Internal error et return

2022-06-09 19:21 UTC, Brawdunoir commented on routes/user.go
> +	c.JSON(http.StatusOK, gin.H{"message": "User deleted", "id": meta.Key})
Virer message

2022-06-12 16:31 UTC, Brawdunoir approved these changes

2022-06-12 16:39 UTC, merged