6 add unit test for crud user and room
Brawdunoir/dionysos-server pull request #29
Opened 2022-07-05 21:38 UTC by Brawdunoir

2022-07-08 18:42 UTC, vazanoir requested changes
Moke rooms and users for every crud tests

2022-07-08 18:42 UTC, vazanoir commented on tests/room_test.go
> +			{Name: "Empty body", Request: utils.Request{Method: method, URL: roomURL, Body: ``}, ResponseCode: http.StatusBadRequest, ResponseBodyRegex: `{"error":".+"}`},
```suggestion
			{Name: "Empty body", Request: utils.Request{Method: method, URL: roomURL, Body: ``}, ResponseCode: http.StatusBadRequest, ResponseBodyRegex: `{"error":".+"}`},
			{Name: "Empty json", Request: utils.Request{Method: method, URL: roomURL, Body: `{}`}, ResponseCode: http.StatusBadRequest, ResponseBodyRegex: `{"error":".+"}`},
```

2022-07-08 18:42 UTC, vazanoir commented on tests/room_test.go
> +			{Name: "Empty body", Request: utils.Request{Method: method, URL: roomURL, Body: ``}, ResponseCode: http.StatusBadRequest, ResponseBodyRegex: `{"error":".+"}`},
Add it for every test like this

2022-07-08 18:42 UTC, vazanoir commented on tests/room_test.go
> +			{Name: "Bad name value", Request: utils.Request{Method: method, URL: roomURL, Body: `{"name":""}`}, ResponseCode: http.StatusBadRequest, ResponseBodyRegex: `{"error":".+"}`},
Add tests for int/object/(nil/null) in values

2022-07-11 20:39 UTC, WhiteDiamondz requested changes
Small fixes in comments, otherwise good to merge once corrected !

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/room_test.go
> +// TestGetRoom test the GetRoom function.
```suggestion
// TestGetRoom tests the GetRoom function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/room_test.go
> +// TestUpdateRoom test the UpdateRoom function.
```suggestion
// TestUpdateRoom tests the UpdateRoom function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/room_test.go
> +// TestDeleteRoom test the DeleteRoom function.
```suggestion
// TestDeleteRoom tests the DeleteRoom function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/user_test.go
> +// TestGetUser test the GetUser function.
```suggestion
// TestGetUser tests the GetUser function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/user_test.go
> +// TestUpdateUser test the UpdateUser function.
```suggestion
// TestUpdateUser tests the UpdateUser function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on tests/user_test.go
> +// TestDeleteUser test the DeleteUser function.
```suggestion
// TestDeleteUser tests the DeleteUser function.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on utils/tests/tests.go
> +// SubTest is an atomic test that include a request and its intended response.
```suggestion
// SubTest is an atomic test that includes a request and its intended response.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on utils/tests/tests.go
> +// Request simple request to be send to the router.
```suggestion
// Request a simple request to be sent to the router.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on utils/tests/tests_create.go
> +// Runs a series of tests for a Create type endpoint.
```suggestion
// Runs a series of tests for the Create type endpoint.
```

2022-07-11 20:39 UTC, WhiteDiamondz commented on utils/tests/tests_rud.go
> +// Runs a series of tests for a Get type endpoint.
```suggestion
// Runs a series of tests for the Get type endpoint.
```

2022-07-11 20:46 UTC, WhiteDiamondz approved these changes
Good to go !

2022-07-11 20:48 UTC, vazanoir approved these changes

2022-07-11 20:49 UTC, merged