65 implement authentication and authorization on certain routes
Brawdunoir/dionysos-server pull request #66
Opened 2022-07-29 21:51 UTC by Brawdunoir

This PR add an authentication middleware. See #65.
This middleware is implemented in all routes except the `/users` on `POST`, because it is our equivalent to /login.

This middleware uses basic auth and returns 401 code if
- `Authorization` header is empty or not well formed
- The password mismatch from the one in DB
It returns 404 code if no user with this id is found in DB

It also sets the found and authenticated user as a context value so it can be retrieved in different routes.
We use this value on `/users/:id` for `PATCH` and `DELETE` requests to assert the request author is the same as the targeted user. If not, we also send a 401 code.

This PR has a lot of changements in tests utils to implement the header and keep the tests running.

2022-07-30 12:10 UTC, WhiteDiamondz commented on routes/user.go
> +	password := make([]byte, 32)
32 ?

2022-07-31 17:18 UTC, Brawdunoir commented on routes/user.go
> +	password := make([]byte, 32)
Indeed, it is fixed

2022-07-31 19:40 UTC, WhiteDiamondz requested changes
Small changes, otherwise almost ready to go through !

2022-07-31 19:40 UTC, WhiteDiamondz commented on tests/middleware_test.go
> +			{Name: "Not well formed authorization header", Request: utils.Request{Method: method, Headers: []utils.Header{{Key: "Authorization", Value: "apikey xxx"}}}, ResponseCode: http.StatusUnauthorized,
```suggestion
			{Name: "Badly formed authorization header", Request: utils.Request{Method: method, Headers: []utils.Header{{Key: "Authorization", Value: "apikey xxx"}}}, ResponseCode: http.StatusUnauthorized, ResponseBodyRegex: `{"error":"User not authorized"}`},
```

2022-07-31 19:40 UTC, WhiteDiamondz commented on utils/routes/conversion.go
> +		return nil, errors.New("value found in context but it was not a user")
In what case could this happen?

2022-07-31 19:40 UTC, WhiteDiamondz commented on routes/user.go
> +	// Create 64 bytes random password
Change to 32 then ?

2022-07-31 19:40 UTC, WhiteDiamondz commented on utils/tests/tests.go
> +	// Target is append to the Test Target URL.
```suggestion
	// Target is appended to the Test Target URL.
```

2022-07-31 19:44 UTC, Brawdunoir commented on utils/routes/conversion.go
> +		return nil, errors.New("value found in context but it was not a user")
None, except if in middleware we don’t set correctly the value of key user.
Basically it should never happen ;)

2022-07-31 19:45 UTC, Brawdunoir commented on routes/user.go
> +	// Create 64 bytes random password
Has been done.

2022-07-31 19:52 UTC, WhiteDiamondz approved these changes

2022-07-31 19:57 UTC, merged